package ghoststate

import (
	"fmt"
	"path"
	"strings"

	"github.com/ianclemence/ghost/pkg/personalcontext"
)

// classifyWorkspaceFile returns the category for a workspace-relative artifact.
// Every path that can appear in a live workspace must be recognized: anything
// unknown fails the export so state can never silently disappear.
func classifyWorkspaceFile(rel string) (Category, error) {
	rel = path.Clean(strings.TrimPrefix(path.Clean(rel), "/"))
	if rel == "." || rel == "" {
		return "", fmt.Errorf("invalid workspace-relative path %q", rel)
	}

	switch {
	case rel == "ghost.db":
		// The database is a runtime index: conversations travel as portable
		// conversations/*.jsonl and the database is rehydrated from them on
		// import, so the binary never crosses machines.
		return CategoryRebound, nil
	case rel == "ghost.db-wal" || rel == "ghost.db-shm":
		return CategoryDisposable, nil
	case strings.HasPrefix(rel, "conversations/"):
		// Versioned, deterministic conversation JSONL: the portable form of a
		// conversation, human-readable and independent of the SQLite schema.
		return CategoryPortable, nil
	case strings.HasPrefix(rel, personalContextDirLogical+"/"):
		// The append-only Personal Context entry log: user-owned, durable,
		// structured context that must migrate between machines. The log
		// itself is the canonical artifact, so the complete revision history
		// travels exactly as stored.
		return CategoryPortable, nil
	case rel == "state/identity.json":
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "state/"):
		// state/state.json routing history, evolution, and the dead
		// trajectory/review/skillimprove/learninggraph dirs are all
		// reconstructible rather than user-owned.
		return CategoryDerived, nil
	case rel == "kanban.json":
		// User planning/workflow boards created through the kanban tool.
		return CategoryPortable, nil
	case rel == ".skills-sync.json":
		// Records which skills came from the skills hub and their versions.
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "sessions/"):
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "memory/"):
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "knowledge/"):
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "skills/"):
		if rel == "skills/.bundled_manifest" {
			// Regenerated by sync; travels for convenience but is not canonical.
			return CategoryDerived, nil
		}
		return CategoryPortable, nil
	case rel == "cron/jobs.json":
		return CategoryPortable, nil
	case strings.HasPrefix(rel, "cron/"):
		return CategoryDerived, nil
	case rel == "USER.md" || rel == "AGENTS.md" || rel == "SOUL.md" ||
		rel == "GHOST.md" || rel == "README.md":
		return CategoryPortable, nil
	case rel == "HEARTBEAT.md" || rel == "heartbeat.log":
		return CategoryDerived, nil
	case strings.HasPrefix(rel, "generated/"):
		// Image-generation tool output; reconstructible by re-running.
		return CategoryDerived, nil
	case strings.HasPrefix(rel, "media/"):
		// TTS output and delegation spill files; tool output, reconstructible.
		return CategoryDerived, nil
	case strings.HasPrefix(rel, "cache/"):
		// Image/model caches; regenerable infrastructure.
		return CategoryDerived, nil
	case strings.HasPrefix(rel, "logs/"):
		// Subagent logs; logs are not Ghost State.
		return CategoryDerived, nil
	case strings.HasPrefix(rel, "tmp/"):
		return CategoryDisposable, nil
	default:
		return "", fmt.Errorf("unclassified workspace artifact %q is not part of Ghost State", rel)
	}
}

// classifyConfigFile returns the category for a file living in the config
// directory (the only non-workspace artifacts a Ghost State export knows).
func classifyConfigFile(name string) (Category, error) {
	switch name {
	case "config.json":
		return CategoryPortable, nil
	case ".secrets.json", ".env":
		return CategorySecret, nil
	default:
		return "", fmt.Errorf("unclassified config artifact %q is not part of Ghost State", name)
	}
}

// config logical paths inside an archive, kept independent of the filesystem
// layout that produced them.
const (
	configDirLogical       = "config"
	configJSONLogical      = "config/config.json"
	configSecretsLogical   = "config/.secrets.json"
	configEnvLogical       = "config/.env"
	manifestArchiveLogical = "manifest.json"
	ghostDBLogical         = "ghost.db"
	identityJSONLogical    = "state/identity.json"
	// personalContextDirLogical is the workspace directory holding the
	// append-only Personal Context entry log. It is derived from the
	// personalcontext package so the portable artifact can never drift from
	// the store's canonical location.
	personalContextDirLogical     = personalcontext.EntriesDir
	personalContextEntriesLogical = personalcontext.EntriesDir + "/" + personalcontext.EntriesFile
)
